### ISSUE TITLE
Helm Chart Checks

### ISSUE THREAD

**Issue by jasperchui** [redhat-certification/chart-verifier#47]
Note rough sizings in person days are included

Required High (GA 5/10 mandatory)

- [x] (Martin) (2 pd) Deployed container images scanned and verified by Red Hat #38 (https://issues.redhat.com/browse/HELM-53)
- [x] (Igor) (10 pd) Run test and include OCP version used for performing the checks #43 
     - [x] enable value overrides
- [x] (Martin) (5 pd) Add annotations to report #67
    - [x] Tool generated annotations 
        - [x] OCP version #43 
        - [x] timestamp, digest #42 
    - [x] Annotations from chart #71
      
 - [x] (Martin) (2pd) Report output to console for collection by partner #65
    - [x] Create Report schema #64
- [x] (Martin) (5 pd) Ability to define which checks are mandatory, optional, experimental (need to categorize current checks)

Required manual checks

- [ ] ~~Chart README.md includes pull secret instructions for private registries if required - will be a manual review of the PR at least for GA.~~

Required Medium (GA 5/10 nice to have)

- [ ] (5 pd) Check to make sure app is not using deprecated APIs (https://issues.redhat.com/browse/HELM-64)
- [ ] (10 pd) Chart.yaml includes keywords mapped to OpenShift Categories #39 (https://issues.redhat.com/browse/HELM-107)
- [ ] (5 pd) Chart includes appropriate license file 

Required not prioritized (pots GA 5/10)

- [ ] (10 pd) Integrate with other Helm Chart Check providers #36 (ie. Stackrox, IBM cv)
- [ ] Chart does not install infra plugins and drivers (network, storage, hardware etc) #37 ((https://issues.redhat.com/browse/HELM-61)
- [ ] Compare minKubeVersion against specific OpenShift release #40 (https://issues.redhat.com/browse/HELM-108)
- [ ] Chart README.md includes prerequisites for installing the chart if it exists

Recommended

- [ ] (Recommended) Chart can be installed without manual prerequisites #41 (https://issues.redhat.com/browse/HELM-62)
- [ ] (Recommended) Chart can be installed without admin privileges (https://issues.redhat.com/browse/HELM-63)

**Comment by mmulholla** [comment]
https://docs.google.com/spreadsheets/d/1RSYpc7oo3bdQ5DyyWr_ExCmLtQ7IFif3KR-xHfMRXMY/edit#gid=0

**Comment by sbose78** [comment]
>  Check to make sure app is not using deprecated APIs

Mid-term/long-term, this is something an external API like kubelinter should help us with?
